project:
  type: book

book:
  title: "Revisiting Shapley Values: A Causal Perspective"
  chapters:
    - index.qmd
    - intro.qmd
    - framework.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt
