project:
  type: book

book:
  title: "Revisiting Shapley Values: A Causal Perspective"
  chapters:
    - index.qmd
    - intro.qmd
    - framework.qmd
    - background.qmd
    - explanations.qmd
    - discussion.qmd
    - conclusion.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly

execute:
  freeze: auto
